version: '3'

services:
  # Serviço MySQL
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    environment:
          - MYSQL_DATABASE=teste
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=user
          - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app_network
  # Serviço Node.js
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - app_network
      - app_nginx
    volumes:
    - ./init:/docker-entrypoint-initdb.d

  # Serviço Nginx
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - app_nginx
    restart: "unless-stopped"

networks:
  app_network:
    driver: bridge
  app_nginx:
    driver: bridge

volumes:
  dbdata:
